
# parsetab.py
# This file is automatically generated. Do not edit.
_tabversion = '3.8'

_lr_method = 'LALR'

_lr_signature = 'FF2340BEA343F557ADB478C1D1F2A61D'
    
_lr_action_items = {'RPAREN':([1,4,7,8,9,10,],[-1,8,-5,-3,-2,-4,]),'ALPHABET':([0,2,5,6,],[1,1,1,1,]),'TIMES':([1,3,4,7,8,9,10,],[-1,7,7,-5,-3,7,7,]),'PLUS':([1,3,4,7,8,9,10,],[-1,5,5,-5,-3,-2,-4,]),'LPAREN':([0,2,5,6,],[2,2,2,2,]),'CONCAT':([1,3,4,7,8,9,10,],[-1,6,6,-5,-3,6,-4,]),'$end':([1,3,7,8,9,10,],[-1,0,-5,-3,-2,-4,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'expression':([0,2,5,6,],[3,4,9,10,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> expression","S'",1,None,None,None),
  ('expression -> ALPHABET','expression',1,'p_expression_alphabet','re_parser.py',34),
  ('expression -> expression PLUS expression','expression',3,'p_expression_plus','re_parser.py',38),
  ('expression -> LPAREN expression RPAREN','expression',3,'p_expression_group','re_parser.py',42),
  ('expression -> expression CONCAT expression','expression',3,'p_expression_concat','re_parser.py',46),
  ('expression -> expression TIMES','expression',2,'p_expression_closure','re_parser.py',50),
]
